Repository prgrms-be-devcourse/NBB1_2_3_Team10, pull requests merged in 2024-11, with the labels that each got.

#16 pullrequest: README.md 구현
  README.md
  src/main/kotlin/org/tenten/bittakotlin/demo/User.java
  src/main/kotlin/org/tenten/bittakotlin/demo/UserController.java
  src/main/kotlin/org/tenten/bittakotlin/demo/UserRepository.java
Labels: 📄Docs

#17 Feat: 회원탈퇴 기능
  src/main/kotlin/org/tenten/bittakotlin/member/controller/MemberController.kt
  src/main/kotlin/org/tenten/bittakotlin/member/service/MemberService.kt
  src/main/kotlin/org/tenten/bittakotlin/member/service/MemberServiceImpl.kt
Labels: ✨Feature

#18 [Refactor]: 회원탈퇴(본인만)
  src/main/kotlin/org/tenten/bittakotlin/member/controller/MemberController.kt
  src/main/kotlin/org/tenten/bittakotlin/security/config/SecurityConfig.kt
Labels: 🔧Refactor

#20 [Feat]: 회원엔티티 예외처리 구현
  src/main/kotlin/org/tenten/bittakotlin/member/controller/advice/MemberControllerAdvice.kt
  src/main/kotlin/org/tenten/bittakotlin/member/exception/MemberException.kt
  src/main/kotlin/org/tenten/bittakotlin/member/exception/MemberTaskException.kt
  src/main/kotlin/org/tenten/bittakotlin/member/service/MemberServiceImpl.kt
Labels: ✨Feature

#24 [Refactor]: ScoutRequest 리팩토링 완료
  src/main/kotlin/org/tenten/bittakotlin/profile/entity/Profile.kt
  src/main/kotlin/org/tenten/bittakotlin/scout/controller/ScoutRequestController.kt
  src/main/kotlin/org/tenten/bittakotlin/scout/entity/ScoutRequest.kt
  src/main/kotlin/org/tenten/bittakotlin/scout/repository/ScoutRequestRepository.kt
  src/main/kotlin/org/tenten/bittakotlin/scout/service/ScoutRequestService.kt
Labels: 🔧Refactor

#26 [Refactor] MemberController, MemberDTO , SecurityConfig
  src/main/kotlin/org/tenten/bittakotlin/jobpost/controller/JobPostViewController.kt
  src/main/kotlin/org/tenten/bittakotlin/member/controller/MemberController.kt
  src/main/kotlin/org/tenten/bittakotlin/member/dto/MemberRequestDTO.kt
  src/main/kotlin/org/tenten/bittakotlin/member/service/MemberService.kt
  src/main/kotlin/org/tenten/bittakotlin/member/service/MemberServiceImpl.kt
  src/main/kotlin/org/tenten/bittakotlin/security/config/SecurityConfig.kt
Labels: 🔧Refactor

#30 [Refactor] uri modify
  src/main/kotlin/org/tenten/bittakotlin/security/config/SecurityConfig.kt
Labels: 🔧Refactor

#33 Feat: 조회수/좋아요 시스템 구현
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/controller/LikeController.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/dto/LikeDTO.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/entity/Like.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/repository/LikeRepository.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/service/LikeService.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/like/service/LikeServiceImpl.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/controller/ViewCountController.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/dto/ViewCountDTO.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/entity/ViewCount.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/repository/ViewCountRepository.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/service/ViewCountService.kt
  src/main/kotlin/org/tenten/bittakotlin/feedInteraction/viewCount/service/ViewCountServiceImpl.kt
  src/main/kotlin/org/tenten/bittakotlin/profile/controller/ProfileController.kt
  src/main/kotlin/org/tenten/bittakotlin/profile/entity/Profile.kt
Labels: ✨Feature

#38 [Feat] Member Swagger
  src/main/kotlin/org/tenten/bittakotlin/member/controller/MemberController.kt
Labels: ✨Feature
